trigger:
  branches:
    include:
      - main  # Only trigger on main branch
  paths:
    exclude:
      - frontend/**  # Prevent unnecessary backend rebuilds
      - backend/**   # Prevent unnecessary frontend rebuilds

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '138f68fc-3f69-468d-b87e-98ba93a0748d'
  containerRegistry: 'jckllybillingacr.azurecr.io'
  imageRepository: 'jckllyazurebillingapp'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build Combined Container Image
    pool:
      name: Default
    steps:
    - task: Docker@2
      displayName: Build and push combined image
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

- stage: Deploy
  displayName: Deploy stage
  jobs:
  - job: Deploy
    displayName: Deploy Combined Container to Azure Web App
    pool:
      name: Default
    steps:
    - task: AzureWebAppContainer@1
      displayName: Deploy to Azure Web App
      inputs:
        azureSubscription: 'AzureBillingApp-Connection'
        appName: 'AnceroBilling'
        containers: '$(containerRegistry)/$(imageRepository):$(tag)'