trigger:
- main

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '138f68fc-3f69-468d-b87e-98ba93a0748d'
  containerRegistry: 'jckllybillingacr.azurecr.io'
  backendImageRepository: 'jckllyazurebillingapp-backend'
  frontendImageRepository: 'jckllyazurebillingapp-frontend'
  backendDockerfilePath: '$(Build.SourcesDirectory)/backend/Dockerfile'
  frontendDockerfilePath: '$(Build.SourcesDirectory)/frontend/Dockerfile'
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build Backend and Frontend Containers
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: |
        echo "Ensuring Docker is running..."
        sudo apt update
        sudo apt install -y docker.io
        sudo systemctl start docker
        sudo systemctl enable docker
        sudo usermod -aG docker $(whoami)
        docker --version
      displayName: Install & Start Docker

    - task: Docker@2
      displayName: Build and push backend image
      inputs:
        command: buildAndPush
        repository: $(backendImageRepository)
        dockerfile: $(backendDockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - script: |
        echo "Checking if frontend/Dockerfile exists..."
        ls -lah $(Build.SourcesDirectory)/frontend/
      displayName: Check Frontend Dockerfile

    - task: Docker@2
      displayName: Build and push frontend image
      inputs:
        command: buildAndPush
        repository: $(frontendImageRepository)
        dockerfile: $(frontendDockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

- stage: Deploy
  displayName: Deploy stage
  jobs:
  - job: Deploy
    displayName: Deploy Backend and Frontend to Azure Web App
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: AzureWebAppContainer@1
      displayName: Deploy Backend to Azure Web App
      inputs:
        azureSubscription: 'AzureBillingApp-Connection'
        appName: 'jcklly-billing-backend'
        containers: '$(containerRegistry)/$(backendImageRepository):$(tag)'

    - task: AzureWebAppContainer@1
      displayName: Deploy Frontend to Azure Web App
      inputs:
        azureSubscription: 'AzureBillingApp-Connection' 
        appName: 'jcklly-billing-frontend' 
        containers: '$(containerRegistry)/$(frontendImageRepository):$(tag)'