version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    environment:
      - ENV=development
    ports:
      - "8000:8000"
      - "3000:3000"
    command: ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]