version: "3.8"

services:
  azurebillingapp:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/bin
      - /app/obj
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "1"
