version: "3.8"

services:
  app:
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    environment:
      - ENV=development
    command: >
      sh -c "uvicorn app:app --host 0.0.0.0 --port 8000 --reload & cd /app/frontend && npm start"